name: Pack-pyinstaller-Linux

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        run: |
          sudo apt update -y && sudo apt upgrade -y
          sudo apt install python3 python3-pip python3-tk zip unzip upx -y
          pip install requests pyinstaller PySimpleGUI retrying
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python3 -m pip install -r requirements.txt
          fi
          chmod +x ./install_realesrgan-ncnn-vulkan.sh
          bash install_realesrgan-ncnn-vulkan.sh --noconfirm

      - name: Install neofetch
        run: |
          sudo apt install neofetch -y
          sudo neofetch

      - name: Pack the py file to exe file with realesrgan-ncnn-vulkan
        run: |
          pyinstaller --add-data "/usr/bin/realesrgan-ncnn-vulkan:." -F ./main.py
          cd ./dist
          ls
          pwd

      - uses: actions/upload-artifact@v3
        with:
          name: Real-ESRGAN-TG-bot-linux
          path: ./dist/main
